<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<UseAppHost>true</UseAppHost> 
    <PublishTrimmed>true</PublishTrimmed>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Dapper.AOT</InterceptorsPreviewNamespaces>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="scripts\migrations\2024081401_Initial.sql" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CliFx" Version="2.3.5" />
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="Concentus.Native" Version="1.5.2" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Dapper.AOT" Version="1.0.31" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="dbup-sqlite" Version="5.0.40" />
    <PackageReference Include="Lazy.Fody" Version="1.11.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageReference Include="PortAudioSharp" Version="0.3.0" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="Terminal.Gui" Version="2.0.0-prealpha.216" />
    <PackageReference Include="YoutubeExplodeMusic" Version="6.4.0-music.1" />
  </ItemGroup>
	
 <ItemGroup>
    <InternalsVisibleTo Include="Tests" />
 </ItemGroup>
	
 <ItemGroup>
    <EmbeddedResource Include="Scripts/Migrations/*.sql" />
 </ItemGroup>
	
		 
 <PropertyGroup>
    <PortAudioPlatform>$(RuntimeIdentifier)</PortAudioPlatform>
    <PortAudioPlatform Condition="'$(PortAudioPlatform)' == '' AND $([MSBuild]::IsOsPlatform('Windows')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64'">win-arm64</PortAudioPlatform>
    <PortAudioPlatform Condition="'$(PortAudioPlatform)' == '' AND $([MSBuild]::IsOsPlatform('Windows')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X86'">win-x86</PortAudioPlatform>
    <PortAudioPlatform Condition="'$(PortAudioPlatform)' == '' AND $([MSBuild]::IsOsPlatform('Windows')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64'">win-x64</PortAudioPlatform>
    <PortAudioPlatform Condition="'$(PortAudioPlatform)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64'">linux-arm64</PortAudioPlatform>
    <PortAudioPlatform Condition="'$(PortAudioPlatform)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X86'">linux-x86</PortAudioPlatform>
    <PortAudioPlatform Condition="'$(PortAudioPlatform)' == '' AND $([MSBuild]::IsOsPlatform('Linux')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64'">linux-x64</PortAudioPlatform>
    <PortAudioPlatform Condition="'$(PortAudioPlatform)' == '' AND $([MSBuild]::IsOsPlatform('OSX')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64'">osx-arm64</PortAudioPlatform>
    <PortAudioPlatform Condition="'$(PortAudioPlatform)' == '' AND $([MSBuild]::IsOsPlatform('OSX')) AND '$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'X64'">osx-x64</PortAudioPlatform>
    <PortAudioFileName Condition="$(PortAudioPlatform.StartsWith('win-'))">portaudio.dll</PortAudioFileName>
    <PortAudioFileName Condition="$(PortAudioPlatform.StartsWith('linux-x'))">libportaudio.so</PortAudioFileName>
    <PortAudioFileName Condition="$(PortAudioPlatform.StartsWith('linux-arm'))">libportaudio.a</PortAudioFileName>
    <PortAudioFileName Condition="$(PortAudioPlatform.StartsWith('osx-'))">libportaudio.dylib</PortAudioFileName>
  </PropertyGroup>

  <Target Name="Download PortAudio before build" BeforeTargets="PreBuildEvent">
    <Exec Command="pwsh -ExecutionPolicy Bypass -File &quot;$(ProjectDir)/DownloadPortAudioBin.ps1&quot; -Platform $(PortAudioPlatform) -OutputPath &quot;$(ProjectDir)/$(PortAudioFileName)&quot;" LogStandardErrorAsError="true" />
    <Copy SourceFiles="$(ProjectDir)/$(PortAudioFileName)" DestinationFolder="$(OutDir)/runtimes/$(PortAudioPlatform)/native" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="Download PortAudio before publish" BeforeTargets="PrepareForPublish">
    <Exec Command="pwsh -ExecutionPolicy Bypass -File &quot;$(ProjectDir)/DownloadPortAudioBin.ps1&quot; -Platform $(PortAudioPlatform) -OutputPath &quot;$(ProjectDir)/$(PortAudioFileName)&quot;" LogStandardErrorAsError="true" />
    <Copy SourceFiles="$(ProjectDir)/$(PortAudioFileName)" DestinationFolder="$(PublishDir)/runtimes/$(PortAudioPlatform)/native" SkipUnchangedFiles="true" />
  </Target>

</Project>