name: .NET

on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
       DeviceName: VirtualSink
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up PulseAudio
      run: |
        sudo apt-get update
        sudo apt-get install -y pulseaudio
    - name: Start PulseAudio
      run: |
        pulseaudio -k || true
        rm -rf $HOME/.config/pulse
        pulseaudio --start
        sleep 30
    - name: Create default PulseAudio virtual sink
      run: |
        pactl load-module module-null-sink sink_name=VirtualSink sink_properties=device.description=VirtualSink
    - name: Verify PulseAudio Setup
      run: |
        pactl list short sinks
        pactl info
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: cd Console && dotnet publish -c Release -o ./output
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: YoutubeConsole
        path: ./Console/output
      
