name: .NET

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up PulseAudio
      run: |
        sudo apt-get update
        sudo apt-get install -y pulseaudio
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: |
        pulseaudio --start
        pactl load-module module-null-sink sink_name=VirtualSink sink_properties=device.description=Virtual_Sink
        pactl set-default-sink VirtualSink
        dotnet test --no-build --verbosity normal
    - name: Publish
      run: cd Console && dotnet publish -c Release -o ./output
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: YoutubeConsole
        path: ./Console/output
